# Generated by Django 4.0.4 on 2022-04-26 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MarketingMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=200)),
                ('notes', models.TextField()),
                ('status', models.CharField(choices=[('C', 'Canceled'), ('D', 'Done'), ('P', 'Pending'), ('S', 'Shifted')], max_length=40)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.employee')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.meetingtype')),
            ],
        ),
    ]
