# Generated by Django 4.0.4 on 2022-05-13 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
        ('engineering', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskName', models.CharField(max_length=300)),
                ('details', models.TextField()),
                ('numberOfMeters', models.IntegerField()),
                ('numberOfWindows', models.IntegerField()),
                ('completedByEmployee', models.BooleanField()),
                ('confirmedBySuperVisor', models.BooleanField()),
                ('confirmedByCustomer', models.BooleanField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.employee')),
                ('moodBoardPartT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engineering.moodboardpart')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engineering.project')),
            ],
        ),
    ]
